(load "abs3.scm")
(define (new-if predicate then-clause else-clause)
    (cond (predicate then-clause)
          (else else-clause)
    )
)
(define (squre x) (* x x))
(define (average x y)
    (/ (+ x y) 2))
(define (good-enough? guess x)
    (< (abs (- (squre guess) x)) 0.0000000001))
(define (improve guess x)
    (average guess (/ x guess)))
(define (sqrt-iter guess x)
    (new-if (good-enough? guess x)
        guess
        (sqrt-iter (improve guess x) x)))
(define (sqrt x)
    (define guess (/ x 2.0))
    (sqrt-iter guess x))