#lang racket

(define (deriv exp var)
    (cond ((number? exp) 0)
          ((variable? exp) (if (same-variable? exp var) 1 0))
          ((sum? exp) (make-sum (deriv (addend exp) var)
                                (deriv (augend exp) var)))
          ((product? exp) 
            (make-sum
                (make-product (mutiplier exp)
                              (deriv (mutiplicand exp) var))
                (make-product (deriv (mutiplier exp) var)
                              (mutiplicand exp))))
          ((exponentiation? exp)
            (make-product 
                (exponent exp)
                (make-product (make-exponentiation 
                                (base exp) 
                                (- (exponent exp) 1))
                              (deriv (base exp) var))))
          (else (error "unknown expression type: DERIV" exp))))

(define (variable? x) (symbol? x))
(define (same-variable? v1 v2)
    (and (variable? v1) (variable? v2) (eq? v1 v2)))
(define (sum? x) (and (pair? x) (eq? (car x) '+)))
(define (product? x) (and (pair? x) (eq? (car x) '*)))
(define (addend x) (cadr x))
(define (augend x) (caddr x))
(define (mutiplier x) (cadr x))
(define (mutiplicand x) (caddr x))
(define (=number? x num) (and (number? x) (= x num)))
(define (make-sum x y)
    (cond ((and (number? x) (number? y)) (+ x y))
          ((=number? x 0) y)
          ((=number? y 0) x)
          (else (list '+ x y))))
(define (make-product x y)
    (cond ((and (number? x) (number? y) (* x y)))
          ((or (=number? x 0) (=number? y 0)) 0)
          ((=number? x 1) y)
          ((=number? y 1) x)
          (else (list '* x y))))
(define (exponentiation? x) (and (pair? x) (eq? (car x) '**)))
(define (base x) (cadr x))
(define (exponent x) (caddr x))
(define (make-exponentiation x y)
    (cond ((=number? y 0) 1)
          ((=number? y 1) x)
          (else (list '** x y))))

(module+ main
    (deriv '(+ x 3) 'x)
    (deriv '(* x y) 'x)
    (deriv '(* (* x y) (+ x 3)) 'x)
    (deriv '(** x 4) 'x)
    (deriv '(** (+ (** x 2) 1) 4) 'x)
    (deriv '(** x 1) 'x)
    (deriv '(** x 2) 'x))
